-- Canonical categories are installed by
-- migrations/20260816120000_seed_default_categories.sql so remote migration
-- workflows and local resets use one category definition list.
--
-- The interface uses its clearly separated TypeScript development listing
-- fixture until a real Supabase project is connected. Do not seed fabricated
-- approved businesses into a production database.
